CREATE TABLE PUBLIC.USER
(
    ID_USER       bigint        NOT NULL AUTO_INCREMENT,
    EMAIL         varchar(255)  NOT NULL,
    NAME          varchar(255)  NOT NULL,
    PASSWORD_HASH varchar(255)  NOT NULL,
    PATRONYMIC    varchar(255)  NOT NULL,
    ROLE          varchar(255)  NOT NULL,
    SURNAME       varchar(255)  NOT NULL,
    INFO          varchar(2000) NULL
);
CREATE TABLE PUBLIC.DIAGNOSIS
(
    ID_DIAGNOSIS    bigint        NOT NULL AUTO_INCREMENT,
    ASSIGNED        timestamp     NULL,
    CURED           timestamp     NULL,
    DESCRIPTION     varchar(2000) NULL,
    NAME            varchar(255)  NULL,
    DOCTOR_ID_USER  bigint        NULL,
    PATIENT_ID_USER bigint        NULL
);
CREATE TABLE PUBLIC.MEDICINE
(
    ID_THERAPY          bigint        NOT NULL AUTO_INCREMENT,
    ASSIGNED            timestamp     NULL,
    DESCRIPTION         varchar(2000) NULL,
    NAME                varchar(255)  NOT NULL,
    COUNT               int           NULL,
    REFILL              date          NULL,
    ASSIGNED_BY_ID_USER bigint        NULL,
    DIAGNOSIS           bigint        NOT NULL
);
CREATE TABLE PUBLIC.TREATMENT
(
    ID_THERAPY          bigint        NOT NULL AUTO_INCREMENT,
    ASSIGNED            timestamp     NULL,
    DESCRIPTION         varchar(2000) NULL,
    NAME                varchar(255)  NOT NULL,
    ROOM                int           NULL,
    ASSIGNED_BY_ID_USER bigint        NULL,
    DIAGNOSIS           bigint        NOT NULL
);
CREATE TABLE PUBLIC.PROCEDURE_APPOINTMENT_DATES
(
    PROCEDURE_ID_THERAPY bigint    NOT NULL,
    APPOINTMENT_DATES    timestamp NULL
);
CREATE TABLE PUBLIC.SURGERY
(
    ID_THERAPY          bigint        NOT NULL AUTO_INCREMENT,
    ASSIGNED            timestamp     NULL,
    DESCRIPTION         varchar(2000) NULL,
    NAME                varchar(255)  NOT NULL,
    DATE                timestamp     NULL,
    ASSIGNED_BY_ID_USER bigint        NULL,
    DIAGNOSIS           bigint        NOT NULL
);

ALTER TABLE PUBLIC.USER ADD CONSTRAINT PK_USER PRIMARY KEY(ID_USER);
CREATE UNIQUE INDEX EMAIL_UNIQUE ON PUBLIC.USER(EMAIL);
ALTER TABLE PUBLIC.DIAGNOSIS ADD CONSTRAINT PK_DIAGNOSIS PRIMARY KEY(ID_DIAGNOSIS);
CREATE INDEX DOCTOR_DIAGNOSIS ON PUBLIC.DIAGNOSIS(DOCTOR_ID_USER);
CREATE INDEX PATIENT_DIAGNOSIS ON PUBLIC.DIAGNOSIS(PATIENT_ID_USER);
ALTER TABLE PUBLIC.MEDICINE ADD CONSTRAINT PK_MEDICINE PRIMARY KEY(ID_THERAPY);
CREATE INDEX MEDICINE_ASSIGNED_BY ON PUBLIC.MEDICINE(ASSIGNED_BY_ID_USER);
CREATE INDEX MEDICINE_ASSIGNED_TO_IDX ON PUBLIC.MEDICINE(DIAGNOSIS);
ALTER TABLE PUBLIC.TREATMENT ADD CONSTRAINT PK_TREATMENT PRIMARY KEY(ID_THERAPY);
CREATE INDEX TREATMENT_ASSIFNED_TO_IDX ON PUBLIC.TREATMENT(DIAGNOSIS);
CREATE INDEX TREATMENT_ASSIGNED_BY ON PUBLIC.TREATMENT(ASSIGNED_BY_ID_USER);
CREATE INDEX APPOINTED_DATES ON PUBLIC.PROCEDURE_APPOINTMENT_DATES(PROCEDURE_ID_THERAPY);
ALTER TABLE PUBLIC.SURGERY ADD CONSTRAINT PK_SURGERY PRIMARY KEY(ID_THERAPY);
CREATE INDEX OPERATION_ASSIGNED_BY1 ON PUBLIC.SURGERY(ASSIGNED_BY_ID_USER);
CREATE INDEX TREATMENT_ASSIFNED_TO_IDX1 ON PUBLIC.SURGERY(DIAGNOSIS);
ALTER TABLE PUBLIC.DIAGNOSIS ADD CONSTRAINT DOCTOR_DIAGNOSIS FOREIGN KEY (DOCTOR_ID_USER) REFERENCES PUBLIC.USER(ID_USER);
ALTER TABLE PUBLIC.DIAGNOSIS ADD CONSTRAINT PATIENT_DIAGNOSIS FOREIGN KEY (PATIENT_ID_USER) REFERENCES PUBLIC.USER(ID_USER);
ALTER TABLE PUBLIC.MEDICINE ADD CONSTRAINT MEDICINE_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY_ID_USER) REFERENCES PUBLIC.USER(ID_USER);
ALTER TABLE PUBLIC.MEDICINE ADD CONSTRAINT MEDICINE_ASSIGNED_TO FOREIGN KEY (DIAGNOSIS) REFERENCES PUBLIC.DIAGNOSIS(ID_DIAGNOSIS);
ALTER TABLE PUBLIC.TREATMENT ADD CONSTRAINT TREATMENT_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY_ID_USER) REFERENCES PUBLIC.USER(ID_USER);
ALTER TABLE PUBLIC.TREATMENT ADD CONSTRAINT TREATMENT_ASSIGNED_TO FOREIGN KEY (DIAGNOSIS) REFERENCES PUBLIC.DIAGNOSIS(ID_DIAGNOSIS);
ALTER TABLE PUBLIC.PROCEDURE_APPOINTMENT_DATES ADD CONSTRAINT APPOINTED_DATES FOREIGN KEY (PROCEDURE_ID_THERAPY) REFERENCES PUBLIC.TREATMENT(ID_THERAPY);
ALTER TABLE PUBLIC.SURGERY ADD CONSTRAINT OPERATION_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY_ID_USER) REFERENCES PUBLIC.USER(ID_USER);
ALTER TABLE PUBLIC.SURGERY ADD CONSTRAINT TRATMENT_ASSIGNED_TO FOREIGN KEY (DIAGNOSIS) REFERENCES PUBLIC.DIAGNOSIS(ID_DIAGNOSIS);