CREATE TABLE PUBLIC.USER
(
    ID_USER       bigint       NOT NULL AUTO_INCREMENT,
    EMAIL         varchar(255) NOT NULL,
    NAME          varchar(255) NOT NULL,
    PASSWORD_HASH varchar(255) NOT NULL,
    PATRONYMIC    varchar(255) NOT NULL,
    ROLE          varchar(255) NOT NULL,
    SURNAME       varchar(255) NOT NULL
);
CREATE TABLE PUBLIC.DIAGNOSIS
(
    ID_DIAGNOSIS    bigint       NOT NULL AUTO_INCREMENT,
    ASSIGNED        timestamp    NULL,
    CURED           timestamp    NULL,
    DESCRIPTION     varchar(255) NULL,
    NAME            varchar(255) NULL,
    DOCTOR_ID_USER  bigint       NULL,
    PATIENT_ID_USER bigint       NULL
);
CREATE TABLE PUBLIC.MEDICINE
(
    ID_THERAPY          bigint       NOT NULL AUTO_INCREMENT,
    ASSIGNED            timestamp    NULL,
    DESCRIPTION         varchar(255) NULL,
    NAME                varchar(255) NOT NULL,
    COUNT               int          NULL,
    REFILL              timestamp    NULL,
    ASSIGNED_BY_ID_USER bigint       NULL
);
CREATE TABLE PUBLIC.DIAGNOSIS_ASSIGNED_MEDICINE
(
    DIAGNOSIS_ID_DIAGNOSIS       bigint NOT NULL,
    ASSIGNED_MEDICINE_ID_THERAPY bigint NOT NULL
);
CREATE TABLE PUBLIC.OPERATION
(
    ID_THERAPY          bigint       NOT NULL AUTO_INCREMENT,
    ASSIGNED            timestamp    NULL,
    DESCRIPTION         varchar(255) NULL,
    NAME                varchar(255) NOT NULL,
    DATE                timestamp    NULL,
    ASSIGNED_BY_ID_USER bigint       NULL
);
CREATE TABLE PUBLIC.DIAGNOSIS_ASSIGNED_OPERATIONS
(
    DIAGNOSIS_ID_DIAGNOSIS         bigint NOT NULL,
    ASSIGNED_OPERATIONS_ID_THERAPY bigint NOT NULL
);
CREATE TABLE PUBLIC.TREATMENT
(
    ID_THERAPY          bigint       NOT NULL AUTO_INCREMENT,
    ASSIGNED            timestamp    NULL,
    DESCRIPTION         varchar(255) NULL,
    NAME                varchar(255) NOT NULL,
    ROOM                int          NULL,
    ASSIGNED_BY_ID_USER bigint       NULL
);
CREATE TABLE PUBLIC.DIAGNOSIS_ASSIGNED_PROCEDURES
(
    DIAGNOSIS_ID_DIAGNOSIS         bigint NOT NULL,
    ASSIGNED_PROCEDURES_ID_THERAPY bigint NOT NULL
);
CREATE TABLE PUBLIC.PROCEDURE_APPOINTMENT_DATES
(
    PROCEDURE_ID_THERAPY bigint    NOT NULL,
    APPOINTMENT_DATES    timestamp NULL
);
ALTER TABLE PUBLIC.USER
    ADD CONSTRAINT PK_USER PRIMARY KEY (ID_USER);
CREATE UNIQUE INDEX EMAIL_UNIQUE ON PUBLIC.USER (EMAIL);
ALTER TABLE PUBLIC.DIAGNOSIS
    ADD CONSTRAINT PK_DIAGNOSIS PRIMARY KEY (ID_DIAGNOSIS);
CREATE INDEX DOCTOR_DIAGNOSIS ON PUBLIC.DIAGNOSIS (DOCTOR_ID_USER);
CREATE INDEX PATIENT_DIAGNOSIS ON PUBLIC.DIAGNOSIS (PATIENT_ID_USER);
ALTER TABLE PUBLIC.MEDICINE
    ADD CONSTRAINT PK_MEDICINE PRIMARY KEY (ID_THERAPY);
CREATE INDEX MEDICINE_ASSIGNED_BY ON PUBLIC.MEDICINE (ASSIGNED_BY_ID_USER);
CREATE INDEX DIAGNOSIS_MEDICINE ON PUBLIC.DIAGNOSIS_ASSIGNED_MEDICINE (ASSIGNED_MEDICINE_ID_THERAPY);
CREATE INDEX MEDICINE_DIAGNOSIS ON PUBLIC.DIAGNOSIS_ASSIGNED_MEDICINE (DIAGNOSIS_ID_DIAGNOSIS);
ALTER TABLE PUBLIC.OPERATION
    ADD CONSTRAINT PK_OPERATION PRIMARY KEY (ID_THERAPY);
CREATE INDEX OPERATION_ASSIGNED_BY ON PUBLIC.OPERATION (ASSIGNED_BY_ID_USER);
CREATE INDEX DIAGNOSIS_OPERATION ON PUBLIC.DIAGNOSIS_ASSIGNED_OPERATIONS (ASSIGNED_OPERATIONS_ID_THERAPY);
CREATE INDEX OPERATION_DIAGNOSIS ON PUBLIC.DIAGNOSIS_ASSIGNED_OPERATIONS (DIAGNOSIS_ID_DIAGNOSIS);
ALTER TABLE PUBLIC.TREATMENT
    ADD CONSTRAINT PK_TREATMENT PRIMARY KEY (ID_THERAPY);
CREATE INDEX TREATMENT_ASSIGNED_BY ON PUBLIC.TREATMENT (ASSIGNED_BY_ID_USER);
CREATE INDEX DIAGNOSIS_THERAPY ON PUBLIC.DIAGNOSIS_ASSIGNED_PROCEDURES (DIAGNOSIS_ID_DIAGNOSIS);
CREATE INDEX THERAPY_DIAGNOSIS ON PUBLIC.DIAGNOSIS_ASSIGNED_PROCEDURES (ASSIGNED_PROCEDURES_ID_THERAPY);
CREATE INDEX APPOINTED_DATES ON PUBLIC.PROCEDURE_APPOINTMENT_DATES (PROCEDURE_ID_THERAPY);
ALTER TABLE PUBLIC.DIAGNOSIS
    ADD CONSTRAINT DOCTOR_DIAGNOSIS FOREIGN KEY (DOCTOR_ID_USER) REFERENCES PUBLIC.USER (ID_USER);
ALTER TABLE PUBLIC.DIAGNOSIS
    ADD CONSTRAINT PATIENT_DIAGNOSIS FOREIGN KEY (PATIENT_ID_USER) REFERENCES PUBLIC.USER (ID_USER);
ALTER TABLE PUBLIC.MEDICINE
    ADD CONSTRAINT MEDICINE_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY_ID_USER) REFERENCES PUBLIC.USER (ID_USER);
ALTER TABLE PUBLIC.DIAGNOSIS_ASSIGNED_MEDICINE
    ADD CONSTRAINT DIAGNOSIS_MEDICINE FOREIGN KEY (ASSIGNED_MEDICINE_ID_THERAPY) REFERENCES PUBLIC.MEDICINE (ID_THERAPY);
ALTER TABLE PUBLIC.DIAGNOSIS_ASSIGNED_MEDICINE
    ADD CONSTRAINT MEDICINE_DIAGNOSIS FOREIGN KEY (DIAGNOSIS_ID_DIAGNOSIS) REFERENCES PUBLIC.DIAGNOSIS (ID_DIAGNOSIS);
ALTER TABLE PUBLIC.OPERATION
    ADD CONSTRAINT OPERATION_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY_ID_USER) REFERENCES PUBLIC.USER (ID_USER);
ALTER TABLE PUBLIC.DIAGNOSIS_ASSIGNED_OPERATIONS
    ADD CONSTRAINT DIAGNOSIS_OPERATION FOREIGN KEY (ASSIGNED_OPERATIONS_ID_THERAPY) REFERENCES PUBLIC.OPERATION (ID_THERAPY);
ALTER TABLE PUBLIC.DIAGNOSIS_ASSIGNED_OPERATIONS
    ADD CONSTRAINT OPERATION_DIAGNOSIS FOREIGN KEY (DIAGNOSIS_ID_DIAGNOSIS) REFERENCES PUBLIC.DIAGNOSIS (ID_DIAGNOSIS);
ALTER TABLE PUBLIC.TREATMENT
    ADD CONSTRAINT TREATMENT_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY_ID_USER) REFERENCES PUBLIC.USER (ID_USER);
ALTER TABLE PUBLIC.DIAGNOSIS_ASSIGNED_PROCEDURES
    ADD CONSTRAINT DIAGNOSIS_THERAPY FOREIGN KEY (DIAGNOSIS_ID_DIAGNOSIS) REFERENCES PUBLIC.DIAGNOSIS (ID_DIAGNOSIS);
ALTER TABLE PUBLIC.DIAGNOSIS_ASSIGNED_PROCEDURES
    ADD CONSTRAINT THERAPY_DIAGNOSIS FOREIGN KEY (ASSIGNED_PROCEDURES_ID_THERAPY) REFERENCES PUBLIC.TREATMENT (ID_THERAPY);
ALTER TABLE PUBLIC.PROCEDURE_APPOINTMENT_DATES
    ADD CONSTRAINT APPOINTED_DATES FOREIGN KEY (PROCEDURE_ID_THERAPY) REFERENCES PUBLIC.TREATMENT (ID_THERAPY);